### ISSUE TITLE
希望添加的 Feature

### ISSUE THREAD

**Issue by BubuYo** [apm1467/zhihu-heartbeat#2]
1. 点开多图想法的图片时，支持左右键切换图片
2. 支持上下键或者 J/K 键来上下滑动 Feed 流
3. 支持 Esc 关闭点开的视频/图片

**Comment by apm1467** [comment]
可以，我过一周有空了看看怎么写

**Comment by apm1467** [comment]
更新了

**Comment by apm1467** [comment]
感谢建议，都很好，我就都加了
