### ISSUE TITLE
卡在了electron

### ISSUE THREAD

**Issue by wishyy** [apm1467/zhihu-heartbeat#4]

**Comment by apm1467** [comment]
？？？

**Comment by apm1467** [comment]
没看懂，出的问题是什么？

**Comment by wishyy** [comment]
哇刚看到回复。。
yarn install v1.15.2
warning ..\..\package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠂ electron    //一直卡在这里，安装electron后还是卡着不动

**Comment by apm1467** [comment]
我在 Windows 下试了一下，确实这步卡了挺久，大概五分钟后才完成。完成后用 `$ yarn start` 可以成功启动程序。

这个问题别人也遇到：https://github.com/yarnpkg/yarn/issues/5268

他们说用 `$ yarn cache clean && yarn install` 清空缓存再重来可以解决，你可以试试。

**Comment by apm1467** [comment]
对了，似乎，卡在那步的时候要敲一下回车，如果你不敲，哪怕 build 好了也会一直卡着不动。我对 Windows 那套也不是很懂……

**Comment by wishyy** [comment]
可以了，谢谢！！
